### ISSUE TITLE
Different outputs in different instances

### ISSUE THREAD

**Issue by ram469** [fixstars/libSGM#10]
Hi,
I am able to compile and run libSGM,the thing is that when I run the executable the output is different for two different runs with the same input images.I am writing the disparity into a bin file and verifying it in the matlab.
           I am using the standard samples provided by the developers.Please help solve the issue.

**Comment by ykitta-fixstars** [comment]
Does "two different run" means running in parallel?

**Comment by ram469** [comment]
Hi ykitta,
I'm sorry for late reply ,two different runs means executing stand alone binary (image sample not movie sample) two times from command line.

**Comment by ykitta-fixstars** [comment]
Could you tell me how did you write bin file?
I checked difference between two running have same input. and no difference is exists.
Here is sample code:
```diff
diff --git a/sample/image/stereosgm_image.cpp b/sample/image/stereosgm_image.cpp
index 33c4812..253422c 100644
--- a/sample/image/stereosgm_image.cpp
+++ b/sample/image/stereosgm_image.cpp
@@ -58,6 +58,16 @@ int main(int argc, char* argv[]) {

        ssgm.execute(left.data, right.data, (void**)&output.data);

+       cv::Mat output2(cv::Size(left.cols, left.rows), CV_8UC1);
+
+       ssgm.execute(left.data, right.data, (void**)&output2.data);
+
+       cv::Mat diff = output - output2;
+       if (countNonZero(diff) > 0)
+               std::cout << "diff exists." << std::endl;
+       else
+               std::cout << "diff doesn't exist." << std::endl;
+
        // show image
        cv::imshow("image", output * 256 / disp_size);
```

**Comment by ram469** [comment]
Hi,
Thank you for your response,I am using "fwrite" to store the "output.data" into a bin file ,before that I am converting the "unsigned char" to "unsigned short"  for comparision purpose.
              And I also checked the code by adding your lines,it results no difference.I don't know why It is so in my case,I am converting the data using "convertTo" in opencv ,does it effect the data?.

**Comment by ykitta-fixstars** [comment]
Hi, I'm sorry for late reply.
I converted `output` from unsigned short to unsigned char before writing `output.data`.
Like this:
```diff
diff --git a/sample/image/stereosgm_image.cpp b/sample/image/stereosgm_image.cpp
index 33c4812..dd51888 100644
--- a/sample/image/stereosgm_image.cpp
+++ b/sample/image/stereosgm_image.cpp
@@ -58,6 +58,15 @@ int main(int argc, char* argv[]) {

    ssgm.execute(left.data, right.data, (void**)&output.data);

+   cv::Mat output2;
+   output.convertTo(output2, CV_16UC1);
+   FILE *fp = fopen("output.bin", "wb");
+   if (fp)
+   {
+       fwrite(output2.data, output2.rows * output2.cols, sizeof(unsigned char) * 2, fp);
+       fclose(fp);
+   }
+
    // show image
    cv::imshow("image", output * 256 / disp_size);
```

I executed twice and compared two binaries using 'cmp' command,
but I didn't recognize difference.
How did you write data and compare binaries?

**Comment by ram469** [comment]
Hi, I'm sorry for very late reply, I am in some other work, the problem is solved. 

Thank you
