### ISSUE TITLE
Sub-pixel Accuracy Use cases

### ISSUE THREAD

**Issue by mohanen** [fixstars/libSGM#21]
Hi, I have some knowledge on how sub-pixel accuracy works and its implementation, but is it worth the effort to do so. Cause what are the actual use cases it might be needed for.  

Thanks and Regards,
Mohanenv B

**Comment by atakagi-fixstars** [comment]
Hi, @mohanen 

The libSGM have now supported sub-pixel estimation.
As with OpenCV, we estimate sub-pixel by parabola fitting, multiply scaling factor, and store disparities as 16bit image.

For more detailed usage, see [header comment](https://github.com/fixstars/libSGM/blob/master/include/libsgm.h) and [reprojection sample](https://github.com/fixstars/libSGM/blob/master/sample/reprojection/stereosgm_reprojection.cpp).

The following is an example of sub-pixel estimation.
The Result figure is bird view of 3D point cloud reprojected from disparity.
With sub-pixel estimation, we get more accurate point cloud.

### Input Image

![left_image](https://user-images.githubusercontent.com/11705642/48242561-114a4800-e41f-11e8-9ecb-37afa3396d0c.png)

### Result

|without sub-pixel estimation|with sub-pixel estimation|
|-|-|
|<img src=https://user-images.githubusercontent.com/11705642/48242575-245d1800-e41f-11e8-9cb3-9f07dfa5b0f3.png width=256>|<img src=https://user-images.githubusercontent.com/11705642/48242578-28893580-e41f-11e8-997d-e287d3d9de1e.png width=256>|
