### ISSUE TITLE
Unexpected timings for path_aggregation kernels

### ISSUE THREAD

**Issue by funmonty** [fixstars/libSGM#24]
Hi, 

- Environment - TX2
- Running - L4T 16.04

I was using your beautiful SGM implementation in CUDA and noted the following things. 

I was looking to up the optimize the performance as my image resolution is big and FPS was too low. So check if there was room for any improvement right from census transform till the consistency check. I must say it is pretty tight and most of them are already optimized. 

But I found a weird behaviour in all the path aggregation kernels. I was using 4 path, So there are 2 horizontal and 2 vertical kernel calls. Each kernel call took around 6-7ms which is good. Profiler also asid all the 4 kernels took 25ms(attached a screenshot of the profiler) concurrently but when I used gettimeofday() to measure the time for the entire path_aggregation process, the result was surprisingly around 45ms+. **There was a huge 20ms difference**. 

![sgm_fps_issue](https://user-images.githubusercontent.com/23055547/51229687-3d37fb80-1983-11e9-98d4-c65b28c4f0b5.png)

In sgm.cu : 
```
gettimeofday(&start, NULL);

m_path_aggregation.enqueue(
			m_census_left.get_output(),
			m_census_right.get_output(),
			width, height,
			penalty1, penalty2,
			stream);

cudaDeviceSynchronize();
gettimeofday(&stop, NULL);
secs = (double)(stop.tv_usec - start.tv_usec) / 1000000 + (double)(stop.tv_sec - start.tv_sec);
printf("--------------PATH AGGREGATION  -> TIME IN MILLISECONDS : %f\n",secs * 1000);
```

**The print here gave 45ms+** where as the profiler suggests all the kernels(2 vertical + 2 horizontal) are executed in 25ms. Is there any other places where the time is being occupied? I don't think there mem copies take too much time as well. And I would be happy to hear it from you about where else the code can be optimized speed-wise? Any leads would be appreciated.

**Comment by funmonty** [comment]
Thanks for the immediate response. 

I checked the example of _sample/movie_ and debugged my issue. It works as you just mentioned. On my way of debugging, I found that the constructor was declared outside the streaming loop which in my case was inside. So for every stream, it would allocate resources and hence was consuming the extra 20ms time. Now, I sorted it out and the delay would occur only in the first iteration which is absolutely fine.

Cheers.

**Comment by atakagi-fixstars** [comment]
Hi, @funmonty

> And I would be happy to hear it from you about where else the code can be optimized speed-wise? Any leads would be appreciated.

Reducing number of paths to 4 is a good choice.
And I often use downscaling when image resolution is big.
If an image is downscaled in width and height by 1/2, the processed pixels in SGM is reduced to 1/4.
Moreover, required disparity size is also reduced to 1/2.

Below is the pseudo code.

```
cv::Mat left, right, disparity;

// downscale input image by half
cv::pydown(left, left);
cv::pydown(right, right);

// compute disparity
sgm.compute(left, right, disparity);

// resize and rescale disparity
cv::resize(disparity, disparity, cv::Size(), 2, 2);
disparity *= 2;
```

Note that, output disparity may contains invalid value (e.g. d=0 or d=-1),
so resizing disparity with interpolation may generate undesirable result 
by being mixed with valid and invalid values.

One possible way to avoid this is resizeing disparity with nearest-neighbor interpolation.
Another way is doing post-process (e.g. LR consistency check) after resizeing.
This needs some modification of source code.

Regards,

**Comment by ynma-hanvo** [comment]
your implementation is really efficient  compared to my own one.      but I noticed that the 4 aggration path each takes about 7 ms,   but there are running on different stream in parallel,   it it possible that  the whole aggration process takes around 7ms instread of 25 ms.
