### ISSUE TITLE
Error with memory allocating using JetsonTX2

### ISSUE THREAD

**Issue by Sid1057** [fixstars/libSGM#30]
Hello, I try to use your library on JetsonTX2, but it fails with error message:

```
OpenCV Error: Gpu API call (unknown error) in allocate, file /home/nvidia/workspace/opencv/modules/core/src/cuda/gpu_mat.cu, line 116
/home/nvidia/workspace/opencv/modules/core/src/cuda/gpu_mat.cu:116: error: (-217) unknown error in function allocate
```

The size of the frame is 128 x 96, so I don't think that the problem is out of the memory in global memory.

Did you see this problem early on some devices?

Best wishes.

**Comment by atakagi-fixstars** [comment]
Hi @Sid1057 

Thank you for your information.

You showed only OpenCV Error, so I don't know whether it is related with libSGM.
Could you tell me how did you use libSGM and where the error occurred?

Regards,

**Comment by Sid1057** [comment]
@atakagi-fixstars , we fix this error. The error was the mismatch of cuda_arch_bin index. For Jetson TX2 we have to use 6.2 when we compile the library.
Excuse me for troubling.
