### ISSUE TITLE
How to set the min dispartiy?

### ISSUE THREAD

**Issue by Micalson** [fixstars/libSGM#36]
Hi, thank you for your perfect code for stereo matching. In your code, the max disparity is set to 128(default), but I can not find where is the min disparity. Could you explain it? Thank you.

Regards

**Comment by Micalson** [comment]
And in opencv, I can set minDisparity and maxDisparity easily.
https://docs.opencv.org/4.0.1/d2/d85/classcv_1_1StereoSGBM.html

**Comment by atakagi-fixstars** [comment]
Hi, @Micalson 

For algorithm simplicity, min dispartiy is not supported in libSGM.
Regards,

**Comment by mohanen** [comment]
There is a work around, you can shift the right image by an offset (min disparity you want to set) to the left (for positive min disparity) and after disparity computation you can add the offset to the disparity values in the map.

But you should be aware handling zero disparity and invalid disparity cause in this implementation both are set to be 0.

**Comment by Micalson** [comment]
Hi, @atakagi-fixstars 
I think this param is very import for stereo matching because when the optical axes of the two cameras are not aligned(In my stereo system, the angle between the optical axis of the cameras is 20 degrees), the min disparity is most likely negative. I suggest you open up this interface. 
Regards,

**Comment by Micalson** [comment]
Hi, @mohanen 
you are right. But I need to spend some work in getting rid of the invalid points. Does it take a lot of work to open this interface? Thank you for your reply.
Regards.

**Comment by atakagi-fixstars** [comment]
Hi, @Micalson 

Thank you for your suggestion.
We keep in mind that as a future task.

**Comment by hahne** [comment]
What implementation effort would you expect to integrate the possibility of having negative disparities?
I am thinking about implementing this myself.

**Comment by atakagi-fixstars** [comment]
HI, @hahne 

Thank you for asking.

> What implementation effort would you expect to integrate the possibility of having negative disparities?

It will be good to fix total dispairity size to 64 or 128 for simplicity.
And, my idea is to subtract `minDisparity`(may be negative value) from image index in accessing right census image for matching. Like this,

```
right_census[y * step + x - minDisparity]
```

After cost aggregation, we gets `W x H x D(64 or 128)` cost volume.
In winner-takes-all, when we get a disparity at minimum cost, add `minDisparity` to that and output.

Regards,

**Comment by sotsuka-fixstars** [comment]
Hi, @Micalson

We have supported min disparity setting at [2.6.0](https://github.com/fixstars/libSGM/releases/tag/2.6.0).
Please check followings for more details.

- [`sgm::StereoSGM::Parameters::min_disparity`](https://github.com/fixstars/libSGM/blob/2.6.0/include/libsgm.h#L79)
- `@attention` in header comments [here](https://github.com/fixstars/libSGM/blob/2.6.0/include/libsgm.h#L128)
- `sample/image` for actual example of this

Thank you for your suggestion!

Sincerely,

**Comment by Micalson** [comment]
@atakagi-fixstars 
It is perfect. Thank you for your work about this. So far ,I have been using the libSGM, and it is effective. Thanks again.

Sincerely,

**Comment by sotsuka-fixstars** [comment]
Hi, @Micalson

Thank you for comment.
We will close this issue.
If we faced with anything related this issue, reopen it.

Sincerely,
