### ISSUE TITLE
Why did it run slowly with my GPU GTX 1070Ti?

### ISSUE THREAD

**Issue by NiuKeke** [fixstars/libSGM#38]

**Comment by NiuKeke** [comment]
The image size is 450*375,and the disparity size is 64.It will cost about 0.2-0.3 seconds ,which is slower than your experiment result.I do not know why.The result is correct.

**Comment by ykitta-fixstars** [comment]
Did you dry-run API call first? First CUDA API call spends much times for initialization.

cf. https://github.com/fixstars/libSGM/issues/6#issuecomment-275967231

**Comment by NiuKeke** [comment]
> Did you dry-run API call first? First CUDA API call spends much times for initialization.
> 
> cf. [#6 (comment)](https://github.com/fixstars/libSGM/issues/6#issuecomment-275967231)

Thank you very much.It is right what you have said.
