### ISSUE TITLE
Why is it incorrect when it comes to SUBPixel Mode?

### ISSUE THREAD

**Issue by NiuKeke** [fixstars/libSGM#40]
Why is it incorrect when it comes to SUBPixel Mode? When the SUBPIXEL Parameter was set to true,the result disparity image value is incorrect .Did I miss something?

**Comment by sotsuka-fixstars** [comment]
@NiuKeke  
Thank you for letting us know this issue.

We tested sub-pixel function via sample/reprojection (https://github.com/fixstars/libSGM/issues/21#issuecomment-437252144) and KITTI benchmark.
Could you provide a case that cause a result incorrect?

Notice that disparity value will be multiplied `StereoSGM::SUBPIXEL_SCALE` if sub-pixel parameter is set true
(i.e. disparity value is going to have 4 fixed point fractional bits).
https://github.com/fixstars/libSGM/blob/707e28b3ee013851abc5220bcb303cccceb88ee5/include/libsgm.h#L122-L125

Sincerely,

**Comment by NiuKeke** [comment]
> @NiuKeke
> Thank you for letting us know this issue.
> We tested sub-pixel function via sample/reprojection (#21 (comment)) and KITTI benchmark.
> Could you provide a case that cause a result incorrect?
> Notice that disparity value will be multiplied StereoSGM::SUBPIXEL_SCALE if sub-pixel parameter is set true
> (i.e. disparity value is going to have 4 fixed point fractional bits).
> 
>   
>     
>       libSGM/include/libsgm.h
>     
>     
>         Lines 122 to 125
>       in
>       707e28b
>     
>     
>     
>     
> 
>         
>           
>            		* @attention 
>         
> 
>         
>           
>            		* You need to allocate dst memory at least width x height x sizeof(element_type) bytes. 
>         
> 
>         
>           
>            		* The element_type is uint8_t for output_depth_bits == 8 and uint16_t for output_depth_bits == 16. 
>         
> 
>         
>           
>            		* Note that dst element value would be multiplied StereoSGM::SUBPIXEL_SCALE if subpixel option was enabled. 
>         
>     
>   
> 
> 
> Sincerely,

I got it .Sorry,I just missed the StereoSGM::SUBPIXEL_SCALE.

**Comment by sotsuka-fixstars** [comment]
Congrats.

I will close this issue.
If you are faced with anything related this issue, reopen it.

**Comment by NiuKeke** [comment]
> Congrats.
> I will close this issue.
> If you are faced with anything related this issue, reopen it.

Ok,thank you very much.
