### ISSUE TITLE
Question in consistency check?

### ISSUE THREAD

**Issue by vishnukumarts** [fixstars/libSGM#43]
In the file named "check_consistency.cu".  
If we have left image with black pixel(0), we are forcing the corresponding disparity value of the pixel value to 0.

Why its necessary to do?

Thanks,

**Comment by sotsuka-fixstars** [comment]
Hi, @vishnukumarts 

libSGM treat black pixel as mask.

For example, images may contain truely black pixel after stereo rectification.
You can see an example of this in the Daimler Urban Segmentation Dataset.
We sometimes want to treat it as invalid.

You can also remove this operation if you don't want that.

Sincerely,
