### ISSUE TITLE
Point clouds are calculated by disparity. Why are point clouds in ladder shape?

### ISSUE THREAD

**Issue by 8BitCatJQW** [fixstars/libSGM#46]

**Comment by NiuKeke** [comment]
> No description provided.
Maybe you have forgotten the subpixel param which you should have set true.

**Comment by 8BitCatJQW** [comment]
> No description provided.
> Maybe you have forgotten the subpixel param which you should have set true.
Thank you for your reply
Here are my Settings, but still with the same problem.
struct Parameters
		{
			int P1;
			int P2;
			float uniqueness;
			bool subpixel;
			Parameters(int P1 = 10, int P2 = 120, float uniqueness = 0.95f, bool subpixel = true) : P1(P1), P2(P2), uniqueness(uniqueness), subpixel(subpixel) {}
		};

**Comment by sotsuka-fixstars** [comment]
Hi, @8BitCatJQW
Thank you for using libSGM.

Where was this issue occurred in?  Our sample or [your repository](https://github.com/8BitCatJQW/testSGMwindows)?

**Comment by 8BitCatJQW** [comment]
> Hi, @8BitCatJQW
> Thank you for using libSGM.
> Where was this issue occurred in?  Our sample or your repository?
> We would apprecite if you tell us more details.

**Comment by 8BitCatJQW** [comment]
> Hi, @8BitCatJQW
> Thank you for using libSGM.
> Where was this issue occurred in?  Our sample or your repository?
> We would apprecite if you tell us more details.
Thank you for your reply。
This is my repository：https://github.com/8BitCatJQW/libsgmIssueDetails
Can you tell me your E-mail?I can send you the results of my experiment.

**Comment by 8BitCatJQW** [comment]
this my code: https://github.com/8BitCatJQW/libsgmIssueDetails

**Comment by sotsuka-fixstars** [comment]
As https://github.com/8BitCatJQW/libsgmIssueDetails/pull/1 was merged, I will close this issue.
If you are faced with anything related this issue, reopen it.

**Comment by 8BitCatJQW** [comment]
> As 8BitCatJQW/libsgmIssueDetails#1 was merged, I will close this issue.
> If you are faced with anything related this issue, reopen it.

ok Thank you very much. It's my fault.

**Comment by DekaiZhu** [comment]
@sotsuka-fixstars hi, thanks for your code! i use your code to calculate the disparity map from a pair of images from a stereo vision system, and then i use this disparity map to calculate the point cloud but i meet some problem. I am sure that i have enabled the sub-pixel mode (which means that 4 bits in the output disparity value are used for fractional part), but the plane in the generated point cloud still looks like a ladder. 
![2020-09-22 09-39-09屏幕截图](https://user-images.githubusercontent.com/24368463/93837106-87749280-fcb7-11ea-9cd9-f50990954a93.png)
I have tried to compute the mean value with several depth maps, but this small ladder is still there, so i wanna know if there are some suitable method to reduce this problem :)

**Comment by sotsuka-fixstars** [comment]
Hi, @DekaiZhu,

> a pair of images from a stereo vision system,

Thank you for finding weakness of libSGM.
If you don't mind, could you share test dataset?
We would like to check it as well.

May be post disparity refinement were needed.
Comparisons are following link.

https://github.com/fixstars/libSGM/issues/20#issuecomment-526442077
