### ISSUE TITLE
OpenCV problem with Ubuntu 14.04 + Cuda 8.0

### ISSUE THREAD

**Issue by Steve3nto** [fixstars/libSGM#5]
I am trying to build the code on my system:

Ubuntu 14.04 LTS
Nvidia Titan X (Maxwell architecture, sm_52)
Cuda 8.0

I have also manually compiled and installed GLFW3 as explained here. Here is the result of cmake ..

[cmake_result.txt](https://github.com/fixstars/libSGM/files/717296/cmake_result.txt)

When I make the project it fails because of some missing openCV functions that are used for target stereo_test.

You can see the error here

[make_result.txt](https://github.com/fixstars/libSGM/files/717298/make_result.txt)

I installed OpenCV from terminal. If I remember correctly it is OpenCV 2.7

What is the problem with my openCV installation? Should I upgrade to CV3 or it should work also with CV2?

**Comment by ykitta-fixstars** [comment]
Hi.
I'm sorry that no description about version.
Please try to build with OpenCV 3.0 or later.
Or, fix CMakeLists.txt and try to run sample/movies with OpenGL.

**Comment by Steve3nto** [comment]
I cannot figure out how to install OpenCV3 without loosing OpenCV2.4 and so all my old code that uses v2.4 doesn't work anymore. Right now I have only 2.4 installed.

Can you please help me modifying the CMakeLists.txt to run sample/movies with OpenGL?

**Comment by Steve3nto** [comment]
Ok, the code builds properly when using OpenCV 3.2. Issue closed
