### ISSUE TITLE
Getting bad disparity for 4k inputs

### ISSUE THREAD

**Issue by sankarshanmugam** [fixstars/libSGM#64]
We get disparity output with lot of holes for 4k input (size:3840x2160).
Does any specific parameter has any restriction such as libSGM parameter, .cu file block/thread size, etc.
Any help towards this are much appreciated.

**Comment by atakagi-fixstars** [comment]
Hi, @sankarshanmugam 

Could you show the output image?

**Comment by sotsuka-fixstars** [comment]
> We get disparity output with lot of holes for 4k input (size:3840x2160).

When 4k input is used, disparity size maybe insufficient.
libSGM supports 64, 128, 256 as disparity size.

We can try followings
- shrinking input image size (recommended)
- maximizing disparity size by `--disp_size=256` option [when `sample/image/stereo_test` used]
- disabling uniqueness check by `--uniqueness=1.0` option [when `sample/image/stereo_test` used]
- disabling LR check by `--LR_max_diff=-1` option [when `sample/image/stereo_test` used]

We can check parameters of libSGM by

- https://github.com/fixstars/libSGM/blob/cad25c9a8024db0784bd841f398c4466e0eb2158/include/libsgm.h#L88-L105
- https://github.com/fixstars/libSGM/blob/cad25c9a8024db0784bd841f398c4466e0eb2158/include/libsgm.h#L121-L134

**Comment by sankarshanmugam** [comment]
> > We get disparity output with lot of holes for 4k input (size:3840x2160).
> 
> When 4k input is used, disparity size maybe insufficient.
> libSGM supports 64, 128, 256 as disparity size.
> 
> We can try followings
> 
> * shrinking input image size (recommended)
> * maximizing disparity size by `--disp_size=256` option [when `sample/image/stereo_test` used]
> * disabling uniqueness check by `--uniqueness=1.0` option [when `sample/image/stereo_test` used]
> * disabling LR check by `--LR_max_diff=-1` option [when `sample/image/stereo_test` used]
> 
> We can check parameters of libSGM by
> 
> * https://github.com/fixstars/libSGM/blob/cad25c9a8024db0784bd841f398c4466e0eb2158/include/libsgm.h#L88-L105
> * https://github.com/fixstars/libSGM/blob/cad25c9a8024db0784bd841f398c4466e0eb2158/include/libsgm.h#L121-L134

Thank you for your support, we are able to get the better Disparity output for disp_size=256

**Comment by sankarshanmugam** [comment]
> Hi, @sankarshanmugam
> 
> Could you show the output image?

Thank you for your aid, we are able to fix the issue with @sotsuka-fixstars suggestion.

**Comment by sotsuka-fixstars** [comment]
@sankarshanmugam 

> we are able to fix the issue

Then, we will close this issue.
If we faced with related this issue, reopen it.
