### ISSUE TITLE
Disparity quality is worse than cpu version

### ISSUE THREAD

**Issue by xiayeqingfeng** [fixstars/libSGM#69]
Hi, thank you for sharing this highly optimized implementation of SGM.

When I check the quality of the disparity map, I notice that the result is worse than the naive CPU implementation. As demonstrated below, the first image is from CPU implementation and second image is the disparity from LibSGM. Edge fattening can be immediately observed in the second image. Especially in the area between fingers, the result from LibSGM contains more noise. The algorithm setup for both image is: 
- 8 path aggregation
- No sub-pixel refinement
- Enable LR check
- P1 = 10, P2 = 150, uniqueness thresh= 0.99
- use center-symmetrical census
- max disparity = 256

![image](https://user-images.githubusercontent.com/70138735/132276404-fa5c7b14-8102-4c4d-99d1-f7ab79278381.png)
![image](https://user-images.githubusercontent.com/70138735/132276416-ea560025-1f5d-4169-8190-805c50269ec8.png)

As I dig deeper, I notice that this difference may come from the aggregation procedure since the result from census transform are the same. However I can't quick understand the code of the aggregation step since its highly optimized implementation.

1. Do you sacrifice the disparity quality for efficiency in the aggregation process? If so, is it possible to do some modifications in order to improve the disparity quality?
2. What factors may cause such different performance between CPU and GPU version implementation?

Thank you for advance!

**Comment by atakagi-fixstars** [comment]
Hi, @xiayeqingfeng 
Thank you for your comments.

> Do you sacrifice the disparity quality for efficiency in the aggregation process?

No. Our naive CPU implementation is in the [test code](https://github.com/fixstars/libSGM/blob/master/test/path_aggregation_test.hpp), and both CPU result and GPU result are the same.

> What factors may cause such different performance between CPU and GPU version implementation?

I have no idea. Your CPU implementation may be different from ours.

Regards,

**Comment by xiayeqingfeng** [comment]
Thank you for your quick reply!
> I have no idea. Your CPU implementation may be different from ours.

The CPU version I tested is this [repo](https://github.com/ethan-li-coding/SemiGlobalMatching/blob/master/SemiGlobalMatching/SemiGlobalMatching.cpp) and the main matching process is [here](https://github.com/ethan-li-coding/SemiGlobalMatching/blob/d6bbee8162f3ef5dbb675069bf7f7c970d8ab0f9/SemiGlobalMatching/SemiGlobalMatching.cpp#L110). The implementation of this CPU version is pretty straightforward.

When comparing the output between different stages of up-mentioned CPU  version and your GPU version, I think the difference in the final disparity result may comes from the aggregation part. But I'm not quite sure since I haven't fully understand your well-optimized GPU implementation of the aggregation process. 


Is it possible that you take a quick look at the mentioned CPU version and check why your GPU implementation gives the worse result?  I'll keep trying to find the reason as well since the efficiency of your implementation is really promising (good job!)

Thanks in advance!

Best Regards

**Comment by atakagi-fixstars** [comment]
Hi, @xiayeqingfeng 

I checked the [repo](https://github.com/ethan-li-coding/SemiGlobalMatching) and found some differences.
The biggest difference is the method of census transform.

Their [census_transform_9x7](https://github.com/ethan-li-coding/SemiGlobalMatching/blob/d6bbee8162f3ef5dbb675069bf7f7c970d8ab0f9/SemiGlobalMatching/sgm_util.cpp#L46) comes from original census transform, which compares center pixel and it's neighbor pixels in 9x7 window. This needs 62 bits to describe a patch of 9×7 pixels

On the other hand, libSGM uses Center-Symmetric Census Transform (CS-CT) described in [this paper](http://www.mi.fu-berlin.de/inf/groups/ag-ki/publications/Semi-Global_Matching/caip2013rsp_fu.pdf), which compares only center-symmetric pairs of pixels. This only needs 31 bits for 9×7 window, and so it's suitable for GPU optimization.

According to the paper, CS-CT(9x7) is slightly worse than original CT(9x7) in KITTI evaluation.
However, we need to consider another factor, the penalty.

The maximum matching cost (hamming distance) between two patches is 62 for CT and 31 for CS-CT.
So the effect of penalty `P1=10` is not equivalent. 
It works stronger against CS-CT and may lead to smoother disparity map.

It may be possible for CS-CT to get sharper result by setting smaller penalty.

Regards,
