### ISSUE TITLE
invalid device function while running the stereo_movie sample

### ISSUE THREAD

**Issue by ram469** [fixstars/libSGM#8]
libSGM/src/check_consistency.cu : 52 invalid device function
I have given an image of size 1200x320 which is divisible by 16 ,yet I am getting the above error.Any suggestion is appreciable.

**Comment by ykitta-fixstars** [comment]
What GPU are you using?
You need to set suitable Compute Capability to CMakeLists.txt.
For example, if you use Kepler architecture GPU, set `-arch=sm_30`.
FYI: https://developer.nvidia.com/cuda-gpus

```diff
diff --git CMakeLists.txt CMakeLists.txt
index ee9f1d1..1984578 100644
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required(VERSION 2.8)

-set(CUDA_ARCH "-arch=sm_50" CACHE STRING "Value of the NVCC -arch option.")
+set(CUDA_ARCH "-arch=sm_30" CACHE STRING "Value of the NVCC -arch option.")

 option(ENABLE_ZED_DEMO "Build a Demo using ZED Camera" OFF)
```

**Comment by ram469** [comment]
Thank you ykitta for your response,I am using nvidia GeForce GT640 which is a kepler architecture GPU.I will apply the patch you provided and let you know the result.

**Comment by ram469** [comment]
The problem is resolved ,thank you for your help.
