### ISSUE TITLE
Dataset link is not working

### ISSUE THREAD

**Issue by ram469** [fixstars/libSGM#9]
Hi ,Can anybody please specify the reference datasets,the link posted in the repository doesn't contain the datasets.

**Comment by ykitta-fixstars** [comment]
Hi,

Thank you for the information.

I don't know why the link is dead.
I found Ground Truth Stixel Dataset seems to be available as an alternative, though.
http://www.6d-vision.com/ground-truth-stixel-dataset

Download goodWeather.zip from that page and unzip. Then you will see "images" directory.
It contains left and right input images.
Notice that this dataset height is odd and this library requires input images must be even.
So it is needed to make image height even. (I removed the last row as before run SGM.)

**Comment by ram469** [comment]
Hi ,
I have checked the dataset,we need to crop it to make it usable,
Thank you.
